### PR TITLE
AIP-8622 v1.8.0 argo controller to support DLQ feature

### PR DESCRIPTION
**Pull request by talebzeghmi**
Building a patched release of Argo 1.8.1 with cherrypick of https://github.com/argoproj/argo-events/commit/2451789f0ac3516d1d666184ffc28dd5418b8717 feat(EventSensor): Dead Letter Queue Trigger (https://github.com/argoproj/argo-events/pull/3199)

_notice:_ That this is against created `feature/zg-1.8` branch that is at `argo-events` tag `1.8.0` that is the version currently running in the cluster (see [code link](https://gitlab.zgtools.net/analytics/artificial-intelligence/ai-platform/aip-infrastructure/aip-k8s-manifests/-/blob/main/base/eventing/argo-events-controller-deployment-patch.yaml#L19))

### CODE REVIEW

**Comment by aaron-arellano** [comment]
by the looks of it your new branch is strictly based off the argo-events tag you are targeting and seems to build all the distributable in the makefile. I found in the past build the dists we do not need lead to a build of over 2 hours. I suggest commenting out those builds like [here](https://github.com/zillow/argo-events/commit/17070e74295274de3b3136316514d3cb2a084857) so the builds do not take long.

**Comment by aaron-arellano** [comment]
is basing this branch off `argo-events tag 1.8.0` to avoid the eventbus issues?

**Comment by talebzeghmi** [comment]
> is basing this branch off `argo-events tag 1.8.0` to avoid the eventbus issues?

Yes, more details about avoiding the upgrade issue here:

* https://gitlab.zgtools.net/analytics/artificial-intelligence/ai-platform/aip-infrastructure/aip-k8s-manifests/-/merge_requests/562
* and https://zillowgroup.atlassian.net/browse/AIP-8356?focusedCommentId=5124099

**Comment by talebzeghmi** [comment]
> by the looks of it your new branch is strictly based off the argo-events tag you are targeting and seems to build all the distributable in the makefile. I found in the past build the dists we do not need lead to a build of over 2 hours. I suggest commenting out those builds like [here](https://github.com/zillow/argo-events/commit/17070e74295274de3b3136316514d3cb2a084857) so the builds do not take long.

thank you! I cherry-picked https://github.com/zillow/argo-events/commit/17070e74295274de3b3136316514d3cb2a084857

**Review by aaron-arellano — APPROVED** [review]
lgtm thanks for making the changes

**Comment by cloudw** [comment]
I'm not understanding how the DLQ trigger works with these code. Should changes in `sensors/listener.go` file of PR https://github.com/argoproj/argo-events/pull/3199/files#diff-2063fd3d31f5b3502235eb28a202e5b2705fad864352c8e06871b1037f30972aR224-R239 be included?

**Review by cloudw — APPROVED** [review]

**Comment by talebzeghmi** [comment]
> I'm not understanding how the DLQ trigger works with these code. Should changes in `sensors/listener.go` file of PR https://github.com/argoproj/argo-events/pull/3199/files#diff-2063fd3d31f5b3502235eb28a202e5b2705fad864352c8e06871b1037f30972aR224-R239 be included?

This cherry pick doesn't include that code block with DlqTrigger into Sensor which is already on v1.9.2 of argo-events, it focuses on the controller and webhook validation.  To include that code I'd also have to cherry pick other Sensor features in the 1.9 branch

**Pull request merged**
